### ISSUE TITLE
Make it smaller dude :)

### ISSUE THREAD

**Issue by HuyHung1408** [Cikappa2904/UWPCalculator#1]
![image](https://user-images.githubusercontent.com/86362423/128587588-6b61dc5a-f110-4bf9-8426-eec82aac7c35.png)
![image](https://user-images.githubusercontent.com/86362423/128587595-05ba8320-ace7-425b-b443-c532418df814.png)

**Comment by Cikappa2904** [comment]
Thanks for the feedback!

I will surely try and make it a bit smaller!

**Comment by HuyHung1408** [comment]
ok nice

**Comment by HuyHung1408** [comment]
Can you release it? I don't have Visual Studio yet.

**Comment by Cikappa2904** [comment]
> Can you release it? I don't have Visual Studio yet.

Ok, I'm going to try. I was working on some features so I hope nothing breaks 😂

**Comment by HuyHung1408** [comment]
Ok, thanks lol
