### ISSUE TITLE
missing nuget package

### ISSUE THREAD

**Issue by star08-web** [Cikappa2904/UWPCalculator#3]
ho provato ad aprire e compilare il codice con visual studio 2019 professional e mi da che alcuni pacchetti nuget non sono stati trovati ho provato a lanciare un comando di ripristino e quello che ottengo è questo

----------------------------------------------------------------------------------
Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore		Errore durante il ripristino di pacchetti NuGet: Errore durante il caricamento della libreria DLL dei tipi. (Eccezione da HRESULT: 0x80029C4A (TYPE_E_CANTLOADLIBRARY))				

Gravità	Codice	Descrizione	Progetto	File	Riga	Stato eliminazione
Errore		The package Microsoft.UI.Xaml with version 2.7.0 could not be found in C:\Users\cikap\.nuget\packages\, C:\Program Files (x86)\Microsoft Visual Studio\Shared\NuGetPackages, C:\Program Files (x86)\Microsoft SDKs\UWPNuGetPackages\. Run a NuGet package restore to download the package.	Calcolatrice			
-------------------------------------------------------------------------------------
qualcuno sa come posso reinstallare questo pacchetto ??

**Comment by Cikappa2904** [comment]
https://docs.microsoft.com/it-it/windows/apps/winui/winui2/getting-started#download-and-install-the-windows-ui-library segui questo

**Comment by star08-web** [comment]
thx
